framework:
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
        default_context:
            json_encode_options: JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT
